apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacinema-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javacinema
  template:
    metadata:
      labels:
        app: javacinema
    spec:
      containers:
        - name: javacinema
          image: javacinema:1.0
          args: ["100", "1000"]
